// Generated by Hive CE
// Do not modify
// Check in to version control

// ignore_for_file: unnecessary_const, require_trailing_commas, document_ignores

import 'package:hive_ce/hive.dart';
import 'package:example/named_import.dart';
import 'package:example/types.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(Class1Adapter());
    registerAdapter(Class2Adapter());
    registerAdapter(ConstructorDefaultsAdapter());
    registerAdapter(EmptyClassAdapter());
    registerAdapter(Enum1Adapter());
    registerAdapter(IterableClassAdapter());
    registerAdapter(NamedImportTypeAdapter());
    registerAdapter(NamedImportsAdapter());
    registerAdapter(NullableTypesAdapter());
  }
}
