targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - unnecessary_const
            - require_trailing_commas
            - unnecessary_breaks
            - document_ignores
