import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:hive_ce/hive.dart';
import 'package:hive_ce_generator/src/helper/helper.dart';
import 'package:hive_ce_generator/src/model/hive_schema.dart';
import 'package:hive_ce_generator/src/model/revived_generate_adapter.dart';
import 'package:hive_ce_generator/src/type_adapter_generator.dart';
import 'package:source_gen/source_gen.dart';
import 'package:yaml/yaml.dart';
import 'package:yaml_writer/yaml_writer.dart';
import 'package:path/path.dart' as path;

/// The comment placed at the top of the schema file
const schemaComment = '''
# Generated by Hive CE
# Manual modifications may be necessary for certain migrations
# Check into version control''';

/// Builder that generates Hive adapters from a GenerateAdapters annotation
class AdaptersGenerator extends GeneratorForAnnotation<GenerateAdapters> {
  @override
  Future<String> generateForAnnotatedElement(
    Element element,
    ConstantReader annotation,
    BuildStep buildStep,
  ) async {
    final library = await buildStep.inputLibrary;
    final revived = RevivedGenerateAdapters(annotation);

    final schemaPath = path.join('lib', 'hive', 'hive_schema.yaml');
    final schemaAsset = buildStep.asset(schemaPath);
    final HiveSchema schema;
    if (await buildStep.canRead(schemaAsset)) {
      final schemaContent = await buildStep.readAsString(schemaAsset);
      schema =
          HiveSchema.fromJson(jsonDecode(jsonEncode(loadYaml(schemaContent))));
    } else {
      schema = HiveSchema(nextTypeId: revived.firstTypeId, types: {});
    }

    // Sort existing types by type ID
    final existingSpecs = revived.specs
        .where((spec) => schema.types.containsKey(spec.type.getDisplayString()))
        .toList()
      ..sort((a, b) {
        final aTypeId = schema.types[a.type.getDisplayString()]!.typeId;
        final bTypeId = schema.types[b.type.getDisplayString()]!.typeId;
        return aTypeId.compareTo(bTypeId);
      });

    // Maintain order of new types
    final newSpecs = revived.specs
        .where(
          (spec) => !schema.types.containsKey(spec.type.getDisplayString()),
        )
        .toList();

    var nextTypeId = schema.nextTypeId;
    final newTypes = <String, HiveSchemaType>{};
    final content = StringBuffer();
    for (final spec in existingSpecs + newSpecs) {
      final typeKey = spec.type.getDisplayString();
      final schemaType = schema.types[typeKey] ??
          HiveSchemaType(typeId: nextTypeId++, nextIndex: 0, fields: {});
      final result = TypeAdapterGenerator.generateTypeAdapter(
        element: spec.type.element!,
        library: library,
        typeId: schemaType.typeId,
        schema: schemaType,
      );

      content.write(result.content);
      newTypes[typeKey] = result.schema!;
    }

    final yaml = YamlWriter()
        .write(HiveSchema(nextTypeId: nextTypeId, types: newTypes).toJson());
    // Do not output the schema file through the buildStep since conflicting
    // output handling will delete it before this generator runs
    // Not the safest thing to do, but there doesn't seem to be a better way
    File(schemaPath).writeAsStringSync(
      '''
$schemaComment
$yaml''',
    );

    return content.toString();
  }
}
