name: example
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  hive_ce_flutter:
    path: ../../hive_flutter
  material_ui: ^1.0.0

dev_dependencies:
  rexios_lints: ^19.0.0
  build_runner: ^2.5.4
  hive_ce_generator:
    path: ../../hive_generator

dependency_overrides:
  hive_ce:
    path: ../../hive
  meta: ^1.18.3

flutter:
  uses-material-design: true
