// Generated by Hive CE
// Do not modify
// Check in to version control

// ignore_for_file: unnecessary_const, require_trailing_commas, document_ignores

import 'package:hive_ce/hive.dart';
import 'package:example/hive/hive_adapters.dart';
import 'package:example/types.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(Class1Adapter());
    registerAdapter(Class2Adapter());
    registerAdapter(ClassSpec1Adapter());
    registerAdapter(ClassSpec2Adapter());
    registerAdapter(ConstructorDefaultsAdapter());
    registerAdapter(EmptyClassAdapter());
    registerAdapter(Enum1Adapter());
    registerAdapter(EnumSpecAdapter());
    registerAdapter(IterableClassAdapter());
    registerAdapter(NamedImportsAdapter());
    registerAdapter(NullableTypesAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  Future<void> registerAdapters() {
    return Future.wait([
      registerAdapter(Class1Adapter()),
      registerAdapter(Class2Adapter()),
      registerAdapter(ClassSpec1Adapter()),
      registerAdapter(ClassSpec2Adapter()),
      registerAdapter(ConstructorDefaultsAdapter()),
      registerAdapter(EmptyClassAdapter()),
      registerAdapter(Enum1Adapter()),
      registerAdapter(EnumSpecAdapter()),
      registerAdapter(IterableClassAdapter()),
      registerAdapter(NamedImportsAdapter()),
      registerAdapter(NullableTypesAdapter()),
    ]);
  }
}
