name: hive_override_example

environment:
  sdk: ^3.9.0

dependencies:
  hive: any
  hive_ce: ^2.8.0

dependency_overrides:
  hive:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 18f92b53295e9eb77ebd4830d905a72cd404a126
      path: overrides/hive
