name: hive_ce_inspector_bridge
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  hive_ce: ^2.8.0+2

dev_dependencies:
  test: ^1.24.0
  rexios_lints: ^8.2.0
