name: example
dependencies:
  hive_ce: any
dev_dependencies:
  rexios_lints: ^8.2.0
  build_runner: any
  hive_ce_generator:
    path: ..
environment:
  sdk: ^3.0.0
dependency_overrides:
  hive_ce:
    path: ../../hive
  hive_ce_generator:
    path: ..
