name: Coverage

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage-hive:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/hive
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Collect coverage
        run: |
          dart pub get
          flutter test --coverage
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
