analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:rexios_lints/flutter/core_extra.yaml

# TODO: Remove this analysis_server_plugin pin. https://github.com/IO-Design-Team/hive_ce/issues/323
plugins:
  rexios_lints:
    version: ^19.0.0
  dependency_overrides:
    analysis_server_plugin: 0.3.20

linter:
  rules:
    migrate_design_widgets: false
